name: CI
on:
pull_request:
schedule:
  - cron: "0 3 * * *"

jobs:
  airflow-demo:
    runs-on: ubuntu-20.04
    env:
      AIRFLOW_HOME: ~/airflow
      AIRFLOW_VERSION: 2.0.1
      PYTHON_VERSION: 3.5
    defaults:
      run:
        working-directory: airflow

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: airflow-demo

      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5

      - name: Install airflow
        run: pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"
        env:
          CONSTRAINT_URL: "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

      - name: Install airflow providers
        run: pip install -r requirements.txt

      - name: Run airflow webserver
        run: airflow webserver --port 8080 &

      - name: Run the airflow scheduler
        run: airflow scheduler &

      - name: Test airflow homepage
        run: curl --silent http://localhost:8080
