name: CI
on:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  airflow-demo:
    runs-on: ubuntu-20.04
    env:
      AIRFLOW_HOME: ~/airflow
      AIRFLOW_VERSION: 2.0.1
    defaults:
      run:
        working-directory: ~/airflow

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ~/airflow

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install airflow
        run: pip install "apache-airflow==${AIRFLOW_VERSION}"

      - name: Install airflow providers
        run: pip install -r requirements.txt

      - name: init the airflow db
        run: airflow db init

      - name: Add a test user
        run: |
          airflow users create \
            --username admin \
            --password secret \
            --firstname Rhys \
            --lastname C \
            --role Admin \
            --email null@nullity.com

      - name: Run airflow webserver
        run: airflow webserver --port 8080 &

      - name: Run the airflow scheduler
        run: airflow scheduler &

      - name: Test airflow homepage
        run: curl --silent http://localhost:8080/home
